schema_version = "1.0.0"

id = "blender_kitsu"
version = "0.1.6"
name = "Blender Kitsu"
tagline = "Blender integration with the Kitsu production tracker system"
maintainer = "Blender Studio"
type = "add-on"
website = "https://studio.blender.org/tools/addons/blender_kitsu"
tags = ["Pipeline"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2025 Paul Golter & Blender Studio",
]
