schema_version = "1.0.0"

id = "brushstroke_tools"
version = "1.0.2"
name = "Brushstroke Tools"
tagline = "Brushstroke painting tools by the Blender Studio"
maintainer = "Simon Thommes <simon@blender.org>"
type = "add-on"

website = "https://studio.blender.org/tools/addons/brushstroke_tools"
tags = ["Geometry Nodes", "Grease Pencil", "Node", ]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2024 Blender Foundation",
]

[permissions]
files = "Read/write brushstroke asset resources from/to disk"