name: Test Studio Tools

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    runs-on: bpy-latest
    steps:
      # clone main repo
      - name: Clone repository
        uses: actions/checkout@v4

      # bpy depends on cp311
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r scripts-blender/tests/requirements.txt
          pip install -r scripts-blender/tests/requirements-dev.txt

      # tests may fail due to the worker not having a window manager
      - name: Run Studio Tools tests
        run: pytest -v --durations=0
