schema_version = "1.0.0"

id = "geonode_shapekeys"
version = "1.0.1"
name = "GeoNode Shape Keys"
tagline = "Sculpt on linked animated characters"
maintainer = "Demeter Dzadik <demeter@blender.org>"
type = "add-on"
website = "https://studio.blender.org/tools/addons/geonode_shapekeys"
tags = ["Rigging", "Animation"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2024 Demeter Dzadik & Blender Studio",
]
[permissions]
files = "To load the necessary GeoNodes from its .blend file"
