schema_version = "1.0.0"

id = "pose_shape_keys"
version = "0.0.2"
name = "Pose Shape Keys"
tagline = "Preserve your shape keys through weight changes, and much more"
maintainer = "Demeter Dzadik <demeter@blender.org>"
type = "add-on"
website = "https://studio.blender.org/tools/addons/pose_shape_keys"
tags = ["Rigging"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2024 Demeter Dzadik & Blender Studio",
]