schema_version = "1.0.0"

id = "latticemagic"
version = "1.0.0"
name = "Lattice Magic"
tagline = "Lattice-based deforming tools"
maintainer = "Demeter Dzadik <demeter@blender.org>"
type = "add-on"
website = "https://studio.blender.org/pipeline/addons/lattice_magic"
tags = ["Rigging", "Animation"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2024 Demeter Dzadik & Blender Studio",
]